//
// This file was automatically generated. Please don't edit by hand.
//

#ifndef HDSTENCILUSAGE_CS_HLSL
#define HDSTENCILUSAGE_CS_HLSL
//
// UnityEngine.Rendering.HighDefinition.StencilBeforeTransparent:  static fields
//
#define STENCILBEFORETRANSPARENT_CLEAR (0)
#define STENCILBEFORETRANSPARENT_REQUIRES_DEFERRED_LIGHTING (2)
#define STENCILBEFORETRANSPARENT_SUBSURFACE_SCATTERING (4)
#define STENCILBEFORETRANSPARENT_TRACE_REFLECTION_RAY (8)
#define STENCILBEFORETRANSPARENT_DECAL (16)
#define STENCILBEFORETRANSPARENT_OBJECT_MOTION_VECTOR (32)
#define STENCILBEFORETRANSPARENT_USER_BIT0 (64)
#define STENCILBEFORETRANSPARENT_USER_BIT1 (128)
#define STENCILBEFORETRANSPARENT_HDRPRESERVED_BITS (63)

//
// UnityEngine.Rendering.HighDefinition.StencilAfterOpaque:  static fields
//
#define STENCILAFTEROPAQUE_CLEAR (0)
#define STENCILAFTEROPAQUE_EXCLUDE_FROM_TAA (2)
#define STENCILAFTEROPAQUE_DISTORTION_VECTOR (4)
#define STENCILAFTEROPAQUE_SMAA (4)
#define STENCILAFTEROPAQUE_TRACE_REFLECTION_RAY (8)
#define STENCILAFTEROPAQUE_RESERVED_BITS (56)
#define STENCILAFTEROPAQUE_USER_BIT0 (64)
#define STENCILAFTEROPAQUE_USER_BIT1 (128)
#define STENCILAFTEROPAQUE_HDRPRESERVED_BITS (63)


#endif
